apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-deployment
  labels:
    app: ubuntu
spec:
  replicas: 3 #tells deployment to run 2 pods matching the templated
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        ports: 
      tolerations:
      - key: "example-key"
        operator: "Exists"
        effect: "NoSchedule"
