apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-v1-deployment
  labels:
    app: ctf-v1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-v1-deployment
  template:
    metadata:
      labels:
        app: ctf-v1-deployment
    spec:
      containers:
      - name: ubuntu
        image: michaelposada/ctf_demo:ctfBeta
      - name: psql
        image: michaelposada/ctf-dbms:psqlv5
        imagePullPolicy: Always
        env: 
          - name: POSTGRES_PASSWORD
            value: "pass"
        envFrom:
          - configMapRef:
                  name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: testdb 
      volumes:
      - name: testdb
        persistentVolumeClaim:
                claimName: postgres-pv-claim-groupName
---
apiVersion: v1
kind: Service
metadata:
  name: ctf-ex-one-ssh-sv
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: ctf-v1-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
   - port: 5432
     targetPort: 5432
     protocol: TCP
     name: psql
  selector:
    app: ctf-v1-deployment
