apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: group200-rolebinding
    namespace: group200
roleRef:
  kind: Role
  name: group200-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: testuser201
  apiGroup:
- kind: User
  name: testuser202
  apiGroup:
