apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-v1-deployment
  labels:
    app: ctf-v1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-v1-deployment
  template:
    metadata:
      labels:
        app: ctf-v1-deployment
    spec:
      containers:
      - name: ctf-beta
        image: michaelposada/ctf_demo:ctfBeta
        ports:
---
apiVersion: v1
kind: Service
metadata:
  name: ctf-ssh-svc
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: ctf-v1-deployment
