apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-toolpod-deployment
  labels:
    app: ctf-toolpod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-toolpod-deployment
  template:
    metadata:
      labels:
        app: ctf-toolpod-deployment
    spec:
      containers:
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
      - name: tool-pod
        image: michaelposada/toolimage:v1
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: toolpod-ssh-svc
spec:
  type: LoadBalancer
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
  selector:
    app: ctf-toolpod-deployment
