apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-v2-deployment
  labels:
    app: ctf-v2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctf-v2-deployment
  template:
    metadata:
      labels:
        app: ctf-v2-deployment
    spec:
      containers:
      - name: php-apache
        image: michaelposada/php-apache:v1
      - name: postgres
        image: michaelposada/ctf2-dbms:psqlv4
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
                  name: postgres-config-ctf2
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: testdb
      volumes:
      - name: testdb
        persistentVolumeClaim:
                claimName: postgres-pv-claim-ctf2-groupName
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web-svc
spec:
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP
     name: web-svc
  selector:
    app: ctf-v2-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-test
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
   - port: 5432
     targetPort: 5432
     protocol: TCP
     name: psql
  selector:
    app: ctf-v2-deployment
